### ISSUE TITLE
Non valid RTOS/Platform: nuttx/olimex-stm32-e407 

### ISSUE THREAD

**Issue by Richard-Haes-Ellis** [micro-ROS/micro-ROS_demobox_demo#2]
It seems that the RTOS nuttx paired with the olimex-stm32-e407 platform is not listed as a valid RTOS/platform while running the create_firmware_ws.sh command. 

```
$ ros2 run micro_ros_setup create_firmware_ws.sh nuttx olimex-stm32-e407
Non valid RTOS/Platform: nuttx/olimex-stm32-e407
Available platforms:
. freertos
+-- crazyflie21
+-- esp32
+-- nucleo_f446re
+-- nucleo_f446ze
+-- nucleo_f746zg
+-- nucleo_f767zi
+-- olimex-stm32-e407
. generate_lib
+-- generic
. host
+-- generic
. mbed
+-- disco_l475vg_iot01a
. raspbian
+-- stretch_v8
+-- buster_v7
+-- buster_v8
. zephyr
+-- discovery_l475_iot1
+-- olimex-stm32-e407
+-- nucleo_f401re
+-- nucleo_h743zi
+-- nucleo_f746zg
```
Any clue why this is?

**Comment by ralph-lange** [comment]
You are using Galactic, right? We are currently switching to NuttX 10 for Galactic and Rolling. I see three options for you:
* Try the new NuttX component, cf. https://github.com/micro-ROS/micro_ros_nuttx_app
* Use another RTOS as the Olimex STM32 E407 may be also used with FreeRTOS or Zephyr
* Use Foxy instead of Galactic

**Comment by Richard-Haes-Ellis** [comment]
Yes! I was using Galactic, will there be a NuttX option in Galactic anythme soon?
Will try out those options. 

Many thanks!

**Comment by pablogs9** [comment]
Hello @Richard-Haes-Ellis, from our part, the [micro-ROS component for Nuttx 10](https://github.com/micro-ROS/micro_ros_nuttx_app) will be the only solution for micro-ROS in Nuttx in Galactic.

Do you have any special requirements for using micro-ROS build system tools?
